// Code generated by mockery v2.20.0. DO NOT EDIT.

package domain

import mock "github.com/stretchr/testify/mock"

// MockTroop is an autogenerated mock type for the Troop type
type MockTroop struct {
	mock.Mock
}

// AddRole provides a mock function with given fields: r
func (_m *MockTroop) AddRole(r Role) {
	_m.Called(r)
}

// GetID provides a mock function with given fields:
func (_m *MockTroop) GetID() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

type mockConstructorTestingTNewMockTroop interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockTroop creates a new instance of MockTroop. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockTroop(t mockConstructorTestingTNewMockTroop) *MockTroop {
	mock := &MockTroop{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
